name: CORDIS to Supabase Sync

# Runs weekly on Monday at 03:00 UTC and can be triggered manually
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run CORDIS to Supabase sync
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_TABLE: cordis_projects
        run: |
          python cordis_to_supabase.py
